<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Qinyi Hu">
<meta name="dcterms.date" content="2025-05-03">

<title>Poisson Regression Examples – Chloe’s Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-d4d76bf8491c20bad77d141916dc28e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Chloe’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#blueprinty-case-study" id="toc-blueprinty-case-study" class="nav-link active" data-scroll-target="#blueprinty-case-study">Blueprinty Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#estimation-of-simple-poisson-model" id="toc-estimation-of-simple-poisson-model" class="nav-link" data-scroll-target="#estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</a></li>
  <li><a href="#estimation-of-poisson-regression-model" id="toc-estimation-of-poisson-regression-model" class="nav-link" data-scroll-target="#estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</a></li>
  </ul></li>
  <li><a href="#airbnb-case-study" id="toc-airbnb-case-study" class="nav-link" data-scroll-target="#airbnb-case-study">AirBnB Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1">Introduction</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression Examples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Qinyi Hu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 3, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="blueprinty-case-study" class="level2">
<h2 class="anchored" data-anchor-id="blueprinty-case-study">Blueprinty Case Study</h2>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Blueprinty is a small firm that makes software for developing blueprints specifically for submitting patent applications to the US patent office. Their marketing team would like to make the claim that patent applicants using Blueprinty’s software are more successful in getting their patent applications approved. Ideal data to study such an effect might include the success rate of patent applications before using Blueprinty’s software and after using it. Unfortunately, such data is not available.</p>
<p>However, Blueprinty has collected data on 1,500 mature (non-startup) engineering firms. The data include each firm’s number of patents awarded over the last 5 years, regional location, age since incorporation, and whether or not the firm uses Blueprinty’s software. The marketing team would like to use this data to make the claim that firms using Blueprinty’s software are more successful in getting their patent applications approved.</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<div id="cell-read-blueprinty" class="cell" data-message="false" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"blueprinty.csv"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="read-blueprinty" class="cell-output cell-output-display" data-execution_count="97">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">patents</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">iscustomer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>Midwest</td>
<td>32.5</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>3</td>
<td>Southwest</td>
<td>37.5</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>4</td>
<td>Northwest</td>
<td>27.0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>3</td>
<td>Northeast</td>
<td>24.5</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3</td>
<td>Southwest</td>
<td>37.0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="blueprinty-info" class="cell" data-message="false" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   patents     1500 non-null   int64  
 1   region      1500 non-null   object 
 2   age         1500 non-null   float64
 3   iscustomer  1500 non-null   int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 47.0+ KB</code></pre>
</div>
</div>
<p>The dataset contains 1,500 observations across 4 columns:</p>
<ul>
<li><p><code>patents</code>: A non-negative integer count of awarded patents over 5 years — this will be our response variable.</p></li>
<li><p><code>region</code>: A categorical variable indicating where the firm is located.</p></li>
<li><p><code>age</code>: A numeric variable indicating the number of years since the firm was incorporated.</p></li>
<li><p><code>iscustomer</code>: A binary indicator (0/1) for whether the firm uses Blueprinty’s software.</p></li>
</ul>
<p>We now examine whether firms that use Blueprinty’s software tend to receive more patents. We do this by comparing the distribution of patents awarded for Blueprinty customers vs.&nbsp;non-customers and the mean number of patents awarded in each group.</p>
<div id="cell-hist-patents-by-group" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Split data by customer status</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>cust <span class="op">=</span> df[df[<span class="st">'iscustomer'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'patents'</span>]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>noncust <span class="op">=</span> df[df[<span class="st">'iscustomer'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'patents'</span>]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate means</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>mean_cust <span class="op">=</span> cust.mean()</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>mean_noncust <span class="op">=</span> noncust.mean()</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histograms</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>plt.hist([noncust, cust], bins<span class="op">=</span><span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">17</span>), label<span class="op">=</span>[<span class="ss">f"Non-Customers (mean=</span><span class="sc">{</span>mean_noncust<span class="sc">:.2f}</span><span class="ss">)"</span>, <span class="ss">f"Customers (mean=</span><span class="sc">{</span>mean_cust<span class="sc">:.2f}</span><span class="ss">)"</span>], </span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>         color<span class="op">=</span>[<span class="st">"#ff7f0e"</span>, <span class="st">"#1f77b4"</span>], edgecolor<span class="op">=</span><span class="st">'white'</span>, rwidth<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>plt.axvline(mean_noncust, color<span class="op">=</span><span class="st">'#ff7f0e'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>plt.axvline(mean_cust, color<span class="op">=</span><span class="st">'#1f77b4'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Number of Patents Awarded"</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Number of Firms"</span>)</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Patent Counts by Blueprinty Customer Status"</span>)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>plt.grid(axis<span class="op">=</span><span class="st">'y'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="hist-patents-by-group" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/hist-patents-by-group-output-1.png" width="758" height="470" class="figure-img"></p>
<figcaption>Histogram of Patents Awarded: Blueprinty Customers vs Non-Customers</figcaption>
</figure>
</div>
</div>
</div>
<p>The histogram compares the distribution of patents awarded between Blueprinty customers (blue) and non-customers (orange). We observe that customers tend to have higher average patent counts — about 4.13 compared to 3.47 for non-customers — as indicated by the vertical dashed lines.</p>
<p>While both distributions overlap considerably, Blueprinty customers are less likely to have zero or one patent and more likely to appear in the higher end of the distribution (e.g., 6 or more patents). This suggests that Blueprinty users, on average, are somewhat more successful in obtaining patents. However, the overlap also highlights that many non-customers perform just as well as customers, underscoring the need for a more rigorous statistical model to isolate the effect of software use from other factors.</p>
<p>Blueprinty customers are not selected at random. It may be important to account for systematic differences in the age and regional location of customers vs non-customers.</p>
<div id="cell-region-age-by-customer" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">9</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Region: stacked bar of customer status</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>region_counts <span class="op">=</span> pd.crosstab(df[<span class="st">'region'</span>], df[<span class="st">'iscustomer'</span>], normalize<span class="op">=</span><span class="st">'index'</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>region_counts.plot(kind<span class="op">=</span><span class="st">'bar'</span>, stacked<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>axs[<span class="dv">0</span>], color<span class="op">=</span>[<span class="st">'#ff7f0e'</span>, <span class="st">'#1f77b4'</span>])</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_title(<span class="st">"Customer Status by Region"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_ylabel(<span class="st">"Percentage of Firms"</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].legend(title<span class="op">=</span><span class="st">"Is Customer"</span>, labels<span class="op">=</span>[<span class="st">"No"</span>, <span class="st">"Yes"</span>], loc<span class="op">=</span><span class="st">'lower left'</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].tick_params(axis<span class="op">=</span><span class="st">'x'</span>, rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Age distribution by customer status</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>df, x<span class="op">=</span><span class="st">'age'</span>, hue<span class="op">=</span><span class="st">'iscustomer'</span>, bins<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>axs[<span class="dv">1</span>], element<span class="op">=</span><span class="st">'step'</span>, stat<span class="op">=</span><span class="st">'density'</span>, common_norm<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].set_title(<span class="st">"Age Distribution by Customer Status"</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].set_xlabel(<span class="st">"Years Since Incorporation"</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].legend(title<span class="op">=</span><span class="st">"Is Customer"</span>, labels<span class="op">=</span>[<span class="st">"No"</span>, <span class="st">"Yes"</span>])</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="region-age-by-customer" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/region-age-by-customer-output-1.png" width="662" height="854" class="figure-img"></p>
<figcaption>Comparison of Region and Age by Customer Status</figcaption>
</figure>
</div>
</div>
</div>
<p>We observe some regional variation in customer status: certain regions have higher proportions of Blueprinty users. For example, customers may be overrepresented in regions with more technology-focused industries or firms with higher patenting activity.</p>
<p>Regarding age, the distribution of firm age is broadly similar across customers and non-customers, but there may be a slight tendency for <strong>Blueprinty customers to be younger on average</strong>. This could reflect greater technology adoption among newer firms or those more actively investing in patent tools.</p>
<p>These differences suggest that <strong>region and age may confound the relationship between Blueprinty use and patent output</strong>, and thus should be included as controls in the Poisson regression model.</p>
</section>
<section id="estimation-of-simple-poisson-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</h3>
<p>Since our outcome variable of interest can only be small integer values per a set unit of time, we can use a Poisson density to model the number of patents awarded to each engineering firm over the last 5 years. We start by estimating a simple Poisson model via Maximum Likelihood.</p>
<p>We assume that the number of patents awarded to each firm over 5 years, denoted <span class="math inline">\(Y_i\)</span>, follows a Poisson distribution:</p>
<p><span class="math display">\[
Y_i \sim \text{Poisson}(\lambda_i)
\]</span></p>
<p>The probability mass function for a Poisson distribution is:</p>
<p><span class="math display">\[
f(Y_i \mid \lambda_i) = \frac{e^{-\lambda_i} \lambda_i^{Y_i}}{Y_i!}
\]</span></p>
<p>Assuming independence across firms, the <strong>likelihood function</strong> for a sample of <span class="math inline">\(n\)</span> firms is:</p>
<p><span class="math display">\[
L(\lambda) = \prod_{i=1}^{n} \frac{e^{-\lambda_i} \lambda_i^{Y_i}}{Y_i!}
\]</span></p>
<p>Taking logs gives the <strong>log-likelihood function</strong>:</p>
<p><span class="math display">\[
\log L(\lambda) = \sum_{i=1}^{n} \left[ -\lambda_i + Y_i \log \lambda_i - \log(Y_i!) \right]
\]</span></p>
<p>In a regression context, we typically model <span class="math inline">\(\lambda_i\)</span> as a function of covariates:</p>
<p><span class="math display">\[
\lambda_i = \exp(X_i \beta)
\]</span></p>
<p>This formulation ensures that <span class="math inline">\(\lambda_i &gt; 0\)</span> for all <span class="math inline">\(i\)</span>, and allows us to estimate <span class="math inline">\(\beta\)</span> using Maximum Likelihood.</p>
<p>To estimate the Poisson model via Maximum Likelihood, we first define the log-likelihood function. This function takes the observed patent counts and a vector of Poisson rate parameters <span class="math inline">\(\lambda\)</span>, and returns the total log-likelihood across all firms.</p>
<div id="a2207a0c" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.special <span class="im">import</span> gammaln</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_log_likelihood(lam, y, dtype<span class="op">=</span><span class="bu">float</span>):</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Computes the log-likelihood of observing y given lambda for a Poisson model.</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co">    - lam: array-like of predicted Poisson means (lambda_i)</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co">    - y: array-like of observed counts (y_i)</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co">    - log-likelihood (float)</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.array(lam)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.array(y)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Avoid log(0)</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.clip(lam, <span class="fl">1e-10</span>, <span class="va">None</span>)</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Apply Poisson log-likelihood formula</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    loglik <span class="op">=</span> np.<span class="bu">sum</span>(<span class="op">-</span>lam <span class="op">+</span> y <span class="op">*</span> np.log(lam) <span class="op">-</span> gammaln(y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> loglik</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To visualize how the Poisson log-likelihood changes with different values of <span class="math inline">\(\lambda\)</span>, we compute the log-likelihood over a range of candidate <span class="math inline">\(\lambda\)</span> values, holding <span class="math inline">\(\lambda\)</span> constant across all observations. This approach assumes a simplified model where all firms are expected to receive the same average number of patents. We then plot the resulting log-likelihood curve.</p>
<p>The peak of the curve represents the Maximum Likelihood Estimate (MLE) of <span class="math inline">\(\lambda\)</span>, which is the value that makes the observed data most probable under the Poisson model.</p>
<div id="cell-plot-likelihood-by-lambda" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use observed Y (patents) as data</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> df[<span class="st">'patents'</span>].values</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a range of lambda values to try</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>lambda_vals <span class="op">=</span> np.linspace(<span class="fl">0.1</span>, <span class="dv">10</span>, <span class="dv">1000</span>) </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute log-likelihood for each λ</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>loglik_vals <span class="op">=</span> [poisson_log_likelihood(lam<span class="op">=</span>np.full_like(Y, l, dtype<span class="op">=</span><span class="bu">float</span>), y<span class="op">=</span>Y) <span class="cf">for</span> l <span class="kw">in</span> lambda_vals]</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Find MLE λ and its log-likelihood</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>max_idx <span class="op">=</span> np.argmax(loglik_vals)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>mle_lambda <span class="op">=</span> lambda_vals[max_idx]</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>mle_loglik <span class="op">=</span> loglik_vals[max_idx]</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>plt.plot(lambda_vals, loglik_vals, color<span class="op">=</span><span class="st">'navy'</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>plt.axvline(mle_lambda, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">"MLE λ"</span>)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>plt.text(mle_lambda <span class="op">+</span> <span class="fl">0.1</span>, mle_loglik <span class="op">-</span> <span class="dv">10000</span>, <span class="ss">f"MLE λ ≈ </span><span class="sc">{</span>mle_lambda<span class="sc">:.3f}</span><span class="ss">"</span>, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Lambda (λ)"</span>)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Log-Likelihood"</span>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Poisson Log-Likelihood across Values of λ"</span>)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="plot-likelihood-by-lambda" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/plot-likelihood-by-lambda-output-1.png" width="758" height="470" class="figure-img"></p>
<figcaption>Log-Likelihood of Poisson Model for Different Lambda Values</figcaption>
</figure>
</div>
</div>
</div>
<p>We evaluate the log-likelihood of the Poisson model across a range of values for the rate parameter <span class="math inline">\(\lambda\)</span>, holding it constant across all observations. The peak of the curve represents the maximum likelihood estimate (MLE) of <span class="math inline">\(\lambda\)</span>.</p>
<p>As shown in the plot, the log-likelihood reaches its maximum when <span class="math inline">\(\lambda \approx\)</span> 3.687, which matches the sample mean of the observed patent counts. This is consistent with the known fact that the MLE of λ in a Poisson model with constant λ is simply the sample mean.</p>
<p>We assume that each observation <span class="math inline">\(Y_i\)</span> is drawn independently from a Poisson distribution:</p>
<p><span class="math display">\[
Y_i \sim \text{Poisson}(\lambda)
\]</span></p>
<p>The likelihood function is:</p>
<p><span class="math display">\[
L(\lambda) = \prod_{i=1}^{n} \frac{e^{-\lambda} \lambda^{Y_i}}{Y_i!}
\]</span></p>
<p>Taking logs gives the log-likelihood:</p>
<p><span class="math display">\[
\log L(\lambda) = \sum_{i=1}^{n} \left( -\lambda + Y_i \log \lambda - \log(Y_i!) \right)
\]</span></p>
<p>Now take the first derivative with respect to <span class="math inline">\(\lambda\)</span>:</p>
<p><span class="math display">\[
\frac{d}{d\lambda} \log L(\lambda) = \sum_{i=1}^{n} \left( -1 + \frac{Y_i}{\lambda} \right)
= -n + \frac{1}{\lambda} \sum_{i=1}^n Y_i
\]</span></p>
<p>Set the derivative equal to zero:</p>
<p><span class="math display">\[
-n + \frac{1}{\lambda} \sum Y_i = 0
\quad \Rightarrow \quad \lambda = \frac{1}{n} \sum Y_i = \bar{Y}
\]</span></p>
<p>So the MLE for <span class="math inline">\(\lambda\)</span> is simply the sample mean:</p>
<p><span class="math display">\[
\hat{\lambda}_{\text{MLE}} = \bar{Y}
\]</span></p>
<p>This result “feels right” because the mean of a Poisson distribution is, by definition, <span class="math inline">\(\lambda\)</span>. When estimating a constant <span class="math inline">\(\lambda\)</span> from independent Poisson observations, the natural estimator is just the average of the data.</p>
<p>We now use numerical optimization to find the MLE for <span class="math inline">\(\lambda\)</span> by maximizing the log-likelihood function. Since <code>scipy.optimize.minimize()</code> minimizes functions, we minimize the negative log-likelihood instead.</p>
<div id="optimize-mle-lambda" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed Y</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> df[<span class="st">'patents'</span>].values</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a wrapper: negative log-likelihood for scalar lambda</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> neg_loglik_scalar(l):</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    lam_vec <span class="op">=</span> np.full(Y.shape, l[<span class="dv">0</span>], dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>poisson_log_likelihood(lam_vec, Y)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial guess (e.g., lambda = 1)</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>initial_guess <span class="op">=</span> [<span class="fl">1.0</span>]</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Optimize</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> minimize(neg_loglik_scalar, initial_guess, bounds<span class="op">=</span>[(<span class="fl">1e-5</span>, <span class="va">None</span>)])</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract MLE</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>mle_lambda <span class="op">=</span> result.x[<span class="dv">0</span>]</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estimated MLE λ from optimization: </span><span class="sc">{</span>result<span class="sc">.</span>x[<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated MLE λ from optimization: 3.6847</code></pre>
</div>
</div>
<p>The function <code>neg_loglik_scalar()</code> returns the negative Poisson log-likelihood given a constant <span class="math inline">\(\lambda\)</span> across all observations. After optimization, we find that the MLE value of <span class="math inline">\(\lambda\)</span> closely matches the sample mean of <code>patents</code>, confirming both our theoretical and visual findings.</p>
</section>
<section id="estimation-of-poisson-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</h3>
<p>Next, we extend our simple Poisson model to a Poisson Regression Model such that <span class="math inline">\(Y_i = \text{Poisson}(\lambda_i)\)</span> where <span class="math inline">\(\lambda_i = \exp(X_i'\beta)\)</span>. The interpretation is that the success rate of patent awards is not constant across all firms (<span class="math inline">\(\lambda\)</span>) but rather is a function of firm characteristics <span class="math inline">\(X_i\)</span>. Specifically, we will use the covariates age, age squared, region, and whether the firm is a customer of Blueprinty.</p>
<p>The following function computes the log-likelihood for this model. It takes as input:</p>
<ul>
<li><p><span class="math inline">\(\beta\)</span>: a vector of regression coefficients</p></li>
<li><p><span class="math inline">\(X\)</span>: a covariate matrix (e.g., age, age squared, region dummies, customer status)</p></li>
<li><p><span class="math inline">\(y\)</span>: observed patent counts</p></li>
</ul>
<p>We return the negative log-likelihood to allow optimization with <code>scipy.optimize.minimize()</code>, which minimizes by default.</p>
<div id="poisson-regression-loglik" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_regression_log_likelihood(beta, y, X):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Log-likelihood function for Poisson regression.</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">    - beta: array-like, shape (p,)</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">    - y: array-like, shape (n,)</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">    - X: array-like, shape (n, p)</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co">    - Negative log-likelihood (float)</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> np.array(beta)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> np.array(X)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.array(y)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute lambda_i = exp(X @ beta)</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    linpred <span class="op">=</span> X <span class="op">@</span> beta</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.exp(linpred)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.clip(lam, <span class="fl">1e-10</span>, <span class="fl">1e6</span>)</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Log-likelihood</span></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    loglik <span class="op">=</span> np.<span class="bu">sum</span>(<span class="op">-</span>lam <span class="op">+</span> y <span class="op">*</span> np.log(lam) <span class="op">-</span> gammaln(y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>loglik</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This function allows us to evaluate how well any given coefficient vector <span class="math inline">\(\beta\)</span> explains the observed patent counts. In the next step, we will use this function to find the MLE of <span class="math inline">\(\beta\)</span> via numerical optimization.</p>
<p>We now estimate the Poisson regression model using our custom log-likelihood function. The covariate matrix <span class="math inline">\(X\)</span> includes:</p>
<ul>
<li>A constant intercept term</li>
<li>Firm age and age squared</li>
<li>Region dummy variables (leaving one region as the reference group)</li>
<li>A binary variable indicating whether the firm is a customer of Blueprinty</li>
</ul>
<p>After estimating the model via maximum likelihood, we compute standard errors using the inverse of the Hessian matrix.</p>
<div id="cell-poisson-mle-regression" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'age_sq'</span>] <span class="op">=</span> df[<span class="st">'age'</span>] <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy variables for region (drop one to avoid multicollinearity)</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>region_dummies <span class="op">=</span> pd.get_dummies(df[<span class="st">'region'</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Design matrix X</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.concat([</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    pd.Series(<span class="dv">1</span>, index<span class="op">=</span>df.index, name<span class="op">=</span><span class="st">'intercept'</span>),  <span class="co"># constant term</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    df[[<span class="st">'age'</span>, <span class="st">'age_sq'</span>]],</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    region_dummies,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    df[[<span class="st">'iscustomer'</span>]]</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Outcome variable y</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'patents'</span>].values</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>X_matrix <span class="op">=</span> X.values</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>initial_beta <span class="op">=</span> np.zeros(X.shape[<span class="dv">1</span>])</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Optimize</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> minimize(</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>    poisson_regression_log_likelihood,</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>    x0<span class="op">=</span>initial_beta,</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    args<span class="op">=</span>(y, X_matrix),</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>    method<span class="op">=</span><span class="st">'BFGS'</span></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated coefficients</span></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="op">=</span> result.x</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Variance-covariance matrix (inverse of Hessian)</span></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>vcov <span class="op">=</span> result.hess_inv</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard errors</span></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> np.sqrt(np.diag(vcov))</span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary table</span></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>summary_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Coefficient'</span>: beta_hat,</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Std. Error'</span>: se</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>}, index<span class="op">=</span>X.columns)</span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a>summary_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="poisson-mle-regression" class="cell-output cell-output-display" data-execution_count="105">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">Std. Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">intercept</td>
<td>-0.509981</td>
<td>0.211822</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">age</td>
<td>0.148705</td>
<td>0.015731</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">age_sq</td>
<td>-0.002972</td>
<td>0.000287</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Northeast</td>
<td>0.029155</td>
<td>0.044500</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Northwest</td>
<td>-0.017575</td>
<td>0.063477</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">South</td>
<td>0.056567</td>
<td>0.057164</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Southwest</td>
<td>0.050564</td>
<td>0.051574</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">iscustomer</td>
<td>0.207607</td>
<td>0.035479</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>To verify our custom MLE implementation, we compare our results with the output of Python’s built-in <code>statsmodels.GLM()</code> function. This function fits a Poisson regression model using iteratively reweighted least squares (IRLS), a standard and numerically stable algorithm.</p>
<p>We use the same design matrix <code>X_matrix</code> and response variable <code>y</code>, specifying a Poisson family with a log link function.</p>
<div id="glm-verification" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Poisson GLM</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> sm.GLM(y, X_matrix, family<span class="op">=</span>sm.families.Poisson())</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>result_glm <span class="op">=</span> model.fit()</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Output summary</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result_glm.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                      y   No. Observations:                 1500
Model:                            GLM   Df Residuals:                     1492
Model Family:                 Poisson   Df Model:                            7
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -3258.1
Date:                Sat, 03 May 2025   Deviance:                       2143.3
Time:                        12:03:48   Pearson chi2:                 2.07e+03
No. Iterations:                     5   Pseudo R-squ. (CS):             0.1360
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.5089      0.183     -2.778      0.005      -0.868      -0.150
x1             0.1486      0.014     10.716      0.000       0.121       0.176
x2            -0.0030      0.000    -11.513      0.000      -0.003      -0.002
x3             0.0292      0.044      0.669      0.504      -0.056       0.115
x4            -0.0176      0.054     -0.327      0.744      -0.123       0.088
x5             0.0566      0.053      1.074      0.283      -0.047       0.160
x6             0.0506      0.047      1.072      0.284      -0.042       0.143
x7             0.2076      0.031      6.719      0.000       0.147       0.268
==============================================================================</code></pre>
</div>
</div>
<p>To make the comparison even more transparent, we compile the coefficient estimates and standard errors from both methods into a single table.</p>
<div id="cell-compare-mle-glm" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine manual MLE and GLM results into one table</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>comparison_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Manual MLE Coef'</span>: beta_hat,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'GLM Coef'</span>: result_glm.params,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Manual SE'</span>: se,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'GLM SE'</span>: result_glm.bse</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>}, index<span class="op">=</span>X.columns)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Round for clarity</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>comparison_table <span class="op">=</span> comparison_table.<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>comparison_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="compare-mle-glm" class="cell-output cell-output-display" data-execution_count="107">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Manual MLE Coef</th>
<th data-quarto-table-cell-role="th">GLM Coef</th>
<th data-quarto-table-cell-role="th">Manual SE</th>
<th data-quarto-table-cell-role="th">GLM SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">intercept</td>
<td>-0.5100</td>
<td>-0.5089</td>
<td>0.2118</td>
<td>0.1832</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">age</td>
<td>0.1487</td>
<td>0.1486</td>
<td>0.0157</td>
<td>0.0139</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">age_sq</td>
<td>-0.0030</td>
<td>-0.0030</td>
<td>0.0003</td>
<td>0.0003</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Northeast</td>
<td>0.0292</td>
<td>0.0292</td>
<td>0.0445</td>
<td>0.0436</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Northwest</td>
<td>-0.0176</td>
<td>-0.0176</td>
<td>0.0635</td>
<td>0.0538</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">South</td>
<td>0.0566</td>
<td>0.0566</td>
<td>0.0572</td>
<td>0.0527</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Southwest</td>
<td>0.0506</td>
<td>0.0506</td>
<td>0.0516</td>
<td>0.0472</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">iscustomer</td>
<td>0.2076</td>
<td>0.2076</td>
<td>0.0355</td>
<td>0.0309</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The table above compares the coefficient estimates and standard errors obtained from our custom Poisson MLE implementation with those produced by the built-in <code>statsmodels.GLM()</code> function. We can find that the estimated coefficients from both methods match to at least four decimal places, confirming that our manual likelihood function and optimization routine were implemented correctly, and the standard errors are also nearly identical, with only minor numerical differences attributable to the optimization algorithm or finite difference approximations.</p>
<p>This agreement provides strong validation that our custom MLE estimation procedure correctly reproduces the results of a professionally implemented Poisson regression. It also reinforces the interpretation of the model: for example, the coefficient on <code>iscustomer</code> is approximately 0.208, suggesting that using Blueprinty’s software is associated with a higher expected patent count, holding other variables constant.</p>
<p>Since Poisson regression coefficients are on the log scale, they are not directly interpretable as raw changes in count outcomes. To better understand the practical effect of using Blueprinty’s software, we conduct a simple simulation:</p>
<p>We create two versions of the dataset:</p>
<ul>
<li><p><code>X_0</code>: identical to the original X, but assumes no firm is a customer (<code>iscustomer = 0</code>)</p></li>
<li><p><code>X_1</code>: identical to X, but assumes all firms are customers (<code>iscustomer = 1</code>)</p></li>
</ul>
<p>We then use the estimated <span class="math inline">\(\hat\beta\)</span> vector to predict expected patent counts under both scenarios. The average difference between these two sets of predictions gives an estimate of the causal effect of Blueprinty’s software on patent output.</p>
<div id="blueprinty-effect-prediction" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create X_0 and X_1</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>X_0 <span class="op">=</span> X.copy()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>X_0[<span class="st">'iscustomer'</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>X_1 <span class="op">=</span> X.copy()</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>X_1[<span class="st">'iscustomer'</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted lambdas</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>y_pred_0 <span class="op">=</span> np.exp(X_0 <span class="op">@</span> beta_hat)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>y_pred_1 <span class="op">=</span> np.exp(X_1 <span class="op">@</span> beta_hat)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Difference</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>diff <span class="op">=</span> y_pred_1 <span class="op">-</span> y_pred_0</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>average_diff <span class="op">=</span> diff.mean()</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Average predicted increase in patents from using Blueprinty: </span><span class="sc">{</span>average_diff<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average predicted increase in patents from using Blueprinty: 0.793</code></pre>
</div>
</div>
<p>The result indicates that, on average, using Blueprinty is associated with an increase of approximately 0.793 patents per firm over a five-year period, holding all other firm characteristics constant.</p>
<p>While this number may appear modest at first glance, it is both statistically significant and practically meaningful in the context of patent production, where the average firm receives fewer than 4 patents over 5 years. This suggests that Blueprinty’s software is a valuable tool for firms looking to increase their patenting success — a claim that the company can reasonably include in its marketing efforts.</p>
</section>
</section>
<section id="airbnb-case-study" class="level2">
<h2 class="anchored" data-anchor-id="airbnb-case-study">AirBnB Case Study</h2>
<section id="introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="introduction-1">Introduction</h3>
<p>AirBnB is a popular platform for booking short-term rentals. In March 2017, students Annika Awad, Evan Lebo, and Anna Linden scraped of 40,000 Airbnb listings from New York City. The data include the following variables:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>- `id` = unique ID number for each unit
- `last_scraped` = date when information scraped
- `host_since` = date when host first listed the unit on Airbnb
- `days` = `last_scraped` - `host_since` = number of days the unit has been listed
- `room_type` = Entire home/apt., Private room, or Shared room
- `bathrooms` = number of bathrooms
- `bedrooms` = number of bedrooms
- `price` = price per night (dollars)
- `number_of_reviews` = number of reviews for the unit on Airbnb
- `review_scores_cleanliness` = a cleanliness score from reviews (1-10)
- `review_scores_location` = a "quality of location" score from reviews (1-10)
- `review_scores_value` = a "quality of value" score from reviews (1-10)
- `instant_bookable` = "t" if instantly bookable, "f" if not</code></pre>
</div>
</div>
</div>
<p>We begin by reading in the Airbnb dataset and performing some light data cleaning. Specifically, we drop any rows with missing values in key modeling variables, such as review scores, price, and room type. We also create dummy variables for categorical features like <code>room_type</code> and <code>instant_bookable</code>, and apply a log transformation to <code>price</code> to reduce skewness.</p>
<div id="cell-load-clean-airbnb" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dataset</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"airbnb.csv"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows with missing values in modeling variables</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>df_clean <span class="op">=</span> df.dropna(subset<span class="op">=</span>[</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'number_of_reviews'</span>, <span class="st">'price'</span>, <span class="st">'room_type'</span>, <span class="st">'instant_bookable'</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'review_scores_cleanliness'</span>, <span class="st">'review_scores_location'</span>, <span class="st">'review_scores_value'</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'bathrooms'</span>, <span class="st">'bedrooms'</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create log-transformed price</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>df_clean[<span class="st">'log_price'</span>] <span class="op">=</span> np.log1p(df_clean[<span class="st">'price'</span>])</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy variables for room_type and instant_bookable</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>room_dummies <span class="op">=</span> pd.get_dummies(df_clean[<span class="st">'room_type'</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>bookable_dummy <span class="op">=</span> (df_clean[<span class="st">'instant_bookable'</span>] <span class="op">==</span> <span class="st">"t"</span>).astype(<span class="bu">int</span>).rename(<span class="st">"instant_bookable_dummy"</span>)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into one dataframe</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>df_model <span class="op">=</span> pd.concat([</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    df_clean[[<span class="st">'number_of_reviews'</span>, <span class="st">'days'</span>, <span class="st">'log_price'</span>,</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>              <span class="st">'review_scores_cleanliness'</span>, <span class="st">'review_scores_location'</span>,</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>              <span class="st">'review_scores_value'</span>, <span class="st">'bathrooms'</span>, <span class="st">'bedrooms'</span>]],</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>    room_dummies,</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>    bookable_dummy</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the cleaned dataset</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>df_model.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="load-clean-airbnb" class="cell-output cell-output-display" data-execution_count="109">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">number_of_reviews</th>
<th data-quarto-table-cell-role="th">days</th>
<th data-quarto-table-cell-role="th">log_price</th>
<th data-quarto-table-cell-role="th">review_scores_cleanliness</th>
<th data-quarto-table-cell-role="th">review_scores_location</th>
<th data-quarto-table-cell-role="th">review_scores_value</th>
<th data-quarto-table-cell-role="th">bathrooms</th>
<th data-quarto-table-cell-role="th">bedrooms</th>
<th data-quarto-table-cell-role="th">Private room</th>
<th data-quarto-table-cell-role="th">Shared room</th>
<th data-quarto-table-cell-role="th">instant_bookable_dummy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>150</td>
<td>3130</td>
<td>4.094345</td>
<td>9.0</td>
<td>9.0</td>
<td>9.0</td>
<td>1.0</td>
<td>1.0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>20</td>
<td>3127</td>
<td>5.442418</td>
<td>9.0</td>
<td>10.0</td>
<td>9.0</td>
<td>1.0</td>
<td>0.0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>116</td>
<td>3038</td>
<td>4.499810</td>
<td>9.0</td>
<td>9.0</td>
<td>9.0</td>
<td>1.0</td>
<td>1.0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>60</td>
<td>2981</td>
<td>5.361292</td>
<td>9.0</td>
<td>9.0</td>
<td>9.0</td>
<td>1.0</td>
<td>1.0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>60</td>
<td>2981</td>
<td>5.525453</td>
<td>10.0</td>
<td>9.0</td>
<td>10.0</td>
<td>1.0</td>
<td>2.0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We now have a cleaned dataset ready for modeling. The outcome variable <code>number_of_reviews</code> is a count variable, which we treat as a proxy for booking volume. The covariates include host characteristics (e.g.&nbsp;cleanliness ratings, room type, log price, etc.) that may help explain variation in review count across listings. We manually add a column of ones to include an intercept term.</p>
<div id="cell-construct-x-y" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract response variable</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df_model[<span class="st">'number_of_reviews'</span>].values</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define covariates: drop the outcome column</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df_model.drop(columns<span class="op">=</span>[<span class="st">'number_of_reviews'</span>])</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add intercept column</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>X.insert(<span class="dv">0</span>, <span class="st">'intercept'</span>, <span class="dv">1</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Store design matrix and column names</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>X_matrix <span class="op">=</span> X.values</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>X_columns <span class="op">=</span> X.columns.tolist()</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview shapes</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>X.shape, y.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="construct-x-y" class="cell-output cell-output-display" data-execution_count="110">
<pre><code>((30160, 11), (30160,))</code></pre>
</div>
</div>
<p>We now have a clean design matrix <code>X_matrix</code> with shape <span class="math inline">\((30160, 11)\)</span> and a corresponding response vector <code>y</code>. In the next step, we will fit a Poisson regression model by maximum likelihood using these inputs.</p>
<p>We now fit a Poisson regression model to the Airbnb data using our custom log-likelihood function and <code>scipy.optimize.minimize()</code>. The outcome variable is the number of reviews (a proxy for bookings), and the predictors include room type, log price, review scores, and listing characteristics.</p>
<div id="cell-fit-airbnb-poisson" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define log-likelihood</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_regression_log_likelihood(beta, y, X):</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    linpred <span class="op">=</span> X <span class="op">@</span> beta</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.exp(linpred)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.clip(lam, <span class="fl">1e-10</span>, <span class="fl">1e6</span>)  <span class="co"># ensure stability</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    loglik <span class="op">=</span> np.<span class="bu">sum</span>(<span class="op">-</span>lam <span class="op">+</span> y <span class="op">*</span> np.log(lam) <span class="op">-</span> gammaln(y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>loglik</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>initial_beta <span class="op">=</span> np.zeros(X_matrix.shape[<span class="dv">1</span>])</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>result_airbnb <span class="op">=</span> minimize(poisson_regression_log_likelihood, x0<span class="op">=</span>initial_beta,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>                         args<span class="op">=</span>(y, X_matrix), method<span class="op">=</span><span class="st">'BFGS'</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Get estimates and standard errors</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="op">=</span> result_airbnb.x</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>vcov <span class="op">=</span> result_airbnb.hess_inv <span class="cf">if</span> <span class="bu">isinstance</span>(result_airbnb.hess_inv, np.ndarray) <span class="cf">else</span> result_airbnb.hess_inv.todense()</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> np.sqrt(np.diag(vcov))</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Create summary table</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>summary_airbnb <span class="op">=</span> pd.DataFrame({</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Coefficient'</span>: beta_hat,</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Std. Error'</span>: se</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>}, index<span class="op">=</span>X_columns).<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>summary_airbnb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fit-airbnb-poisson" class="cell-output cell-output-display" data-execution_count="111">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">Std. Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">intercept</td>
<td>3.0133</td>
<td>0.0221</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">days</td>
<td>0.0001</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">log_price</td>
<td>0.1311</td>
<td>0.0035</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">review_scores_cleanliness</td>
<td>0.1088</td>
<td>0.0016</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">review_scores_location</td>
<td>-0.0973</td>
<td>0.0019</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">review_scores_value</td>
<td>-0.0795</td>
<td>0.0019</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">bathrooms</td>
<td>-0.1452</td>
<td>0.0047</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">bedrooms</td>
<td>0.0465</td>
<td>0.0025</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Private room</td>
<td>0.0866</td>
<td>0.0038</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Shared room</td>
<td>-0.1050</td>
<td>0.0096</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">instant_bookable_dummy</td>
<td>0.3520</td>
<td>0.0032</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The table summarizes the maximum likelihood estimates of the regression coefficients and their corresponding standard errors. These results quantify the association between listing characteristics and the expected number of reviews (a proxy for bookings) on Airbnb.</p>
<p>This table reports the estimated coefficients and standard errors from the Poisson regression model predicting the number of reviews, which we use as a proxy for booking volume. Since we are using a log-link function, each coefficient reflects the expected change in the log number of reviews for a one-unit change in the corresponding variable, holding all other variables constant.</p>
<p>We can interpret from the table that:</p>
<ul>
<li><code>log_price</code> (0.1311): Listings with higher prices tend to receive more reviews. This may reflect that higher-end listings are more visible or attract more attention.</li>
<li><code>review_scores_cleanliness</code> (0.1088): Higher cleanliness scores are strongly associated with more reviews, indicating guest satisfaction contributes to engagement.</li>
<li><code>review_scores_location</code> and <code>review_scores_value</code>: Surprisingly, both have negative coefficients. This could reflect expectations bias — listings in great locations may receive fewer marginal reviews due to less surprise or variance in experience.</li>
<li><code>bathrooms</code> (−0.1452): Listings with more bathrooms tend to receive fewer reviews, possibly because larger properties are used less frequently or are higher-end and niche.</li>
<li>Room Type:
<ul>
<li><code>Private room</code> (0.0866): Surprisingly positive, possibly due to affordability and appeal to solo travelers.</li>
<li><code>Shared room</code> (−0.1050): Negative as expected — these may be less popular due to privacy concerns.</li>
</ul></li>
<li><code>instant_bookable_dummy</code> (0.3520): This is one of the strongest effects in the model. Since <span class="math inline">\(\exp(0.3520) \approx 1.42\)</span>, we interpret this as: listings that support instant booking receive approximately 42% more reviews, on average, than comparable listings that do not.</li>
</ul>
<p>These findings align well with platform dynamics: clean, bookable, affordably priced listings tend to perform better in terms of guest engagement, as reflected in review counts.</p>
<p>To make the regression coefficients easier to interpret, we exponentiate them. This transforms each coefficient from a log scale into an incidence rate ratio (IRR). An IRR greater than 1 indicates a positive effect on the number of reviews, while a value less than 1 indicates a negative effect.</p>
<div id="cell-exp-beta-table" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>X_columns <span class="op">=</span> [</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'intercept'</span>, <span class="st">'days'</span>, <span class="st">'log_price'</span>, <span class="st">'review_scores_cleanliness'</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'review_scores_location'</span>, <span class="st">'review_scores_value'</span>, <span class="st">'bathrooms'</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'bedrooms'</span>, <span class="st">'Private room'</span>, <span class="st">'Shared room'</span>, <span class="st">'instant_bookable_dummy'</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute exp(beta) and 95% confidence intervals</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>exp_coef <span class="op">=</span> np.exp(beta_hat)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>lower_ci <span class="op">=</span> np.exp(beta_hat <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>upper_ci <span class="op">=</span> np.exp(beta_hat <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into table</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>exp_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'exp(Coefficient)'</span>: exp_coef,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Lower 95% CI'</span>: lower_ci,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Upper 95% CI'</span>: upper_ci</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>}, index<span class="op">=</span>X_columns).<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>exp_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="exp-beta-table" class="cell-output cell-output-display" data-execution_count="112">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">exp(Coefficient)</th>
<th data-quarto-table-cell-role="th">Lower 95% CI</th>
<th data-quarto-table-cell-role="th">Upper 95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">intercept</td>
<td>20.355</td>
<td>19.493</td>
<td>21.255</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">days</td>
<td>1.000</td>
<td>1.000</td>
<td>1.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">log_price</td>
<td>1.140</td>
<td>1.132</td>
<td>1.148</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">review_scores_cleanliness</td>
<td>1.115</td>
<td>1.112</td>
<td>1.118</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">review_scores_location</td>
<td>0.907</td>
<td>0.904</td>
<td>0.911</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">review_scores_value</td>
<td>0.924</td>
<td>0.920</td>
<td>0.927</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">bathrooms</td>
<td>0.865</td>
<td>0.857</td>
<td>0.873</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">bedrooms</td>
<td>1.048</td>
<td>1.043</td>
<td>1.053</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Private room</td>
<td>1.090</td>
<td>1.082</td>
<td>1.098</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Shared room</td>
<td>0.900</td>
<td>0.884</td>
<td>0.917</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">instant_bookable_dummy</td>
<td>1.422</td>
<td>1.413</td>
<td>1.431</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The table reports <span class="math inline">\(\exp(\beta)\)</span> for each variable, along with 95% confidence intervals. For example, the IRR for <code>instant_bookable_dummy</code> is 1.422, meaning that listings with instant booking enabled are predicted to receive 42.2% more reviews, on average, compared to those that are not. A variable like <code>review_scores_location</code> has an IRR of 0.907, suggesting a 9.3% decrease in expected review count per unit increase in location score — a counterintuitive result that may reflect deeper behavioral patterns.</p>
<p>To assess the robustness of our findings, we now estimate a simpler Poisson regression model using a reduced set of predictors. This model includes only core listing characteristics that are known before any guest stays: price, room type, exposure time (<code>days</code>), and booking mechanism (<code>instant_bookable</code>). We exclude review-based scores and amenities.</p>
<p>This helps isolate the effects of variables that are directly under host control at listing time.</p>
<div id="cell-alt-model" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build reduced X matrix</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>X_alt <span class="op">=</span> df_model[[<span class="st">'log_price'</span>, <span class="st">'days'</span>, <span class="st">'Private room'</span>, <span class="st">'Shared room'</span>, <span class="st">'instant_bookable_dummy'</span>]].copy()</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>X_alt.insert(<span class="dv">0</span>, <span class="st">'intercept'</span>, <span class="dv">1</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>X_alt_matrix <span class="op">=</span> X_alt.values</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>X_alt_columns <span class="op">=</span> X_alt.columns.tolist()</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Define outcome</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>y_alt <span class="op">=</span> df_model[<span class="st">'number_of_reviews'</span>].values</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>initial_beta_alt <span class="op">=</span> np.zeros(X_alt_matrix.shape[<span class="dv">1</span>])</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>result_alt <span class="op">=</span> minimize(poisson_regression_log_likelihood, x0<span class="op">=</span>initial_beta_alt,</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>                      args<span class="op">=</span>(y_alt, X_alt_matrix), method<span class="op">=</span><span class="st">'BFGS'</span>)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract results</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>beta_alt <span class="op">=</span> result_alt.x</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>vcov_alt <span class="op">=</span> result_alt.hess_inv <span class="cf">if</span> <span class="bu">isinstance</span>(result_alt.hess_inv, np.ndarray) <span class="cf">else</span> result_alt.hess_inv.todense()</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>se_alt <span class="op">=</span> np.sqrt(np.diag(vcov_alt))</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Create table</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>summary_alt <span class="op">=</span> pd.DataFrame({</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Coefficient'</span>: beta_alt,</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Std. Error'</span>: se_alt</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>}, index<span class="op">=</span>X_alt_columns).<span class="bu">round</span>(<span class="dv">4</span>)</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>summary_alt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="alt-model" class="cell-output cell-output-display" data-execution_count="113">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">Std. Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">intercept</td>
<td>2.4058</td>
<td>0.0137</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">log_price</td>
<td>0.1018</td>
<td>0.0026</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">days</td>
<td>0.0001</td>
<td>0.0000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Private room</td>
<td>0.0570</td>
<td>0.0033</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Shared room</td>
<td>-0.1355</td>
<td>0.0093</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">instant_bookable_dummy</td>
<td>0.3598</td>
<td>0.0031</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This reduced model captures the influence of pricing, availability, and room type on expected review counts, while omitting subjective post-stay feedback.</p>
<p>The table above reports the coefficients from a reduced Poisson regression model using only key listing characteristics that are known prior to guest interaction. These include price (log-transformed), room type, number of days listed, and whether the listing is instantly bookable.</p>
<p>We can find that:</p>
<ul>
<li><code>log_price</code> (0.1018): Listings with higher prices are associated with more reviews, though the effect is slightly smaller than in the full model. This suggests price still plays a role even when review-based variables are excluded.</li>
<li><code>days</code> (0.0001): Longer-listed properties receive more reviews, as expected. The effect is small per day but compounds over time.</li>
<li>Room Type:
<ul>
<li><code>Private room</code> remains positive and significant, suggesting some demand for more affordable options.</li>
<li><code>Shared room</code> has a stronger negative effect (−0.1355) than in the full model, likely because this model does not control for review-based user experiences.</li>
</ul></li>
<li><code>instant_bookable_dummy</code> (0.3598): The effect of instant booking is even stronger in this reduced model. Exponentiating the coefficient:<br>
<span class="math inline">\(\exp(0.3598) \approx 1.43\)</span>, meaning listings with instant booking enabled receive 43% more reviews than those without.</li>
</ul>
<p>Overall, this simpler model performs well and confirms the robustness of key insights from the full model. It emphasizes that hosts can meaningfully influence booking performance through pricing strategy, room configuration, and booking settings — all of which are controllable pre-listing factors.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>